# file: .github/workflows/hello-world.yml
name: hexlet-my-first-workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # run – произвольная bash-команда
      - run: make say-hello